name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit on all files
        run: uv run pre-commit run -a

      - name: Lint with ruff
        run: uv run ruff check --fix

      - name: Type check with mypy
        run: uv run mypy

      - name: Run fast tests
        run: uv run pytest -m "not slow" -k "not integration"

      - name: Report failure
        if: failure()
        run: |
          echo "::error::PR validation checks failed. Please fix the issues and push again."
          echo "Run the following commands locally to debug:"
          echo "  uv run pre-commit run -a"
          echo "  uv run ruff check --fix"
          echo "  uv run mypy"
          echo "  uv run pytest -m 'not slow' -k 'not integration'"
          exit 1

  docs-build-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: website/package-lock.json

      - name: Install documentation dependencies
        run: |
          cd website
          npm ci

      - name: Build documentation (validation only)
        run: |
          cd website
          npm run build

      - name: Report documentation build failure
        if: failure()
        run: |
          echo "::error::Documentation build failed. Please fix the issues before merging."
          echo "Run the following commands locally to debug:"
          echo "  cd website"
          echo "  npm ci"
          echo "  npm run build"
          exit 1