name: Test Installation

on:
  push:
    branches: [main, develop]
  pull_request:
  release:
    types: [published, prereleased]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  test-pip-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
        install-method: ['source', 'wheel']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install from source
        if: matrix.install-method == 'source'
        run: |
          python -m venv test-env
          test-env/bin/pip install -e .
          
      - name: Install from wheel
        if: matrix.install-method == 'wheel'
        run: |
          python -m venv test-env
          test-env/bin/pip install build
          test-env/bin/python -m build --wheel
          test-env/bin/pip install dist/*.whl
          
      - name: Verify installation
        run: |
          test-env/bin/python -c "import oboyu; print(oboyu.__version__)"
          test-env/bin/oboyu --help
          
      - name: Run basic functionality test
        run: |
          test-env/bin/oboyu health check
          
  test-docker-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Build wheel for Docker tests
        run: |
          pip install build
          python -m build --wheel
          
      - name: Build and test Docker environments
        run: |
          docker-compose -f docker-compose.test.yml build
          docker-compose -f docker-compose.test.yml up --exit-code-from test-pip-source test-pip-source
          docker-compose -f docker-compose.test.yml up --exit-code-from test-pip-wheel test-pip-wheel
          docker-compose -f docker-compose.test.yml up --exit-code-from test-pip-editable test-pip-editable
          docker-compose -f docker-compose.test.yml up --exit-code-from test-uv test-uv
          
  test-installation-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install test dependencies
        run: |
          pip install pytest build
          
      - name: Run installation validation tests
        run: |
          pip install -e .
          pytest tests/test_installation_validation.py -v
          
      - name: Run wheel content validation tests
        run: |
          pytest tests/test_wheel_content_validation.py -v